### ISSUE TITLE
.ico and .webp extensions preview

### ISSUE THREAD

**Issue by Aresenka** [die-coding/yii2-dropify#1]
Please, add those image extensions to bower asset bundle in /dist/js/dropify.js:44 and /src/js/dropify.js:26
Now it show only icon with file extension name

**Comment by wanforge** [comment]
Thank you, now it can be used on the latest updates or on the branch master.

Commit [https://github.com/die-coding/yii2-dropify/commit/e3a1b3affdc34304a678e9f00313ee871f49cade](https://github.com/die-coding/yii2-dropify/commit/e3a1b3affdc34304a678e9f00313ee871f49cade)
Release [v0.2.1](https://github.com/die-coding/yii2-dropify/releases/tag/v0.2.1)
